name: SAM Deploy SND, SND2, DEV

on:
  push:  
    branches: [ $default-branch ]

jobs:
  call-snd-deploy:
    uses: mutual-of-enumclaw/nucleus-deployment-pipeline/.github/workflows/nucleus-deploy-sam-stack.yml@main
    with:
      region: 'us-west-2'
      environment_name: 'snd'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.SANDBOX_DEPLOY_USER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SANDBOX_DEPLOY_USER_AWS_SECRET_ACCESS_KEY }}
      MS_TEAMS_WEBHOOK_URI:  ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  call-snd2-deploy:
    uses: mutual-of-enumclaw/nucleus-deployment-pipeline/.github/workflows/nucleus-deploy-sam-stack.yml@main
    with:
      region: 'us-east-1'
      environment_name: 'snd2'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.SANDBOX_DEPLOY_USER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SANDBOX_DEPLOY_USER_AWS_SECRET_ACCESS_KEY }}
      MS_TEAMS_WEBHOOK_URI:  ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  call-dev-deploy:
    uses: mutual-of-enumclaw/nucleus-deployment-pipeline/.github/workflows/nucleus-deploy-sam-stack.yml@main
    with:
      region: 'us-west-2'
      environment_name: 'dev'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.GENDEV_DEPLOY_USER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GENDEV_DEPLOY_USER_AWS_SECRET_ACCESS_KEY }}
      MS_TEAMS_WEBHOOK_URI:  ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
